services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"
    volumes:
      - ./server:/app
    entrypoint: ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:80"]

  frontend:
    build:
      context: ./air-notebook
      dockerfile: Dockerfile
    command: ["npm", "start"]
    ports:
      - "3000:3000"
    volumes:
      - ./air-notebook:/app

  db:
    image: postgres:15
    container_name: air-notebook-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: AirNotebookDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data